import type {
  ActivityItem,
  AnalyticsData,
  BackgroundPreset,
  NetworkUser,
  QSLCard,
  QSLTemplate,
  UserProfile,
} from "@/types";

export const currentUser: UserProfile = {
  id: "1",
  callsign: "K2ABC",
  name: "Alex Turner",
  avatar: "https://i.pravatar.cc/150?u=k2abc",
  location: "New York, USA",
  country: "USA",
  ituZone: "ITU Zone 8",
  bio: "Passionate HF operator since 2015. Love DX chasing and contesting. 73!",
  stationSetup: "Yaesu FT-991A, Elecraft KX3, Icom IC-7300",
  antennaSetup: "G5RV Jr., End-fed half-wave, 2m/70cm vertical",
  qslInfo: "eQSL, LoTW, Direct",
  email: "alex@example.com",
  phone: "+1 555-0123",
  onAir: true,
  socialLinks: {
    website: "https://k2abc.example.com",
    facebook: "https://facebook.com/k2abc",
    youtube: "https://youtube.com/@k2abc",
    linkedin: "https://linkedin.com/in/k2abc",
    twitter: "https://x.com/k2abc",
  },
  backgroundImage:
    "https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&q=80",
  profileViews: 1524,
  profileSearches: 312,
  cardsReceived: 32,
  cardsSent: 22,
  joinedAt: "2023-03-15",
};

export const users: UserProfile[] = [
  currentUser,
  {
    id: "2",
    callsign: "DL9XX",
    name: "Max Mustermann",
    avatar: "https://i.pravatar.cc/150?u=dl9xx",
    location: "Musterstadt, Germany",
    country: "Germany",
    ituZone: "ITU Zone 28",
    bio: "VHF/UHF enthusiast. Member of local ham club.",
    stationSetup: "Kenwood TS-590SG",
    antennaSetup: "X-50 vertical, Moxon for 6m",
    qslInfo: "LoTW, Direct",
    email: "max@example.de",
    phone: "+49 123 456789",
    onAir: false,
    socialLinks: { website: "https://dl9xx.example.de" },
    profileViews: 890,
    profileSearches: 145,
    cardsReceived: 18,
    cardsSent: 15,
    joinedAt: "2022-08-20",
  },
  {
    id: "3",
    callsign: "JA1XYZ",
    name: "Yuki Tanaka",
    avatar: "https://i.pravatar.cc/150?u=ja1xyz",
    location: "Tokyo, Japan",
    country: "Japan",
    ituZone: "ITU Zone 45",
    bio: "CW operator and JOTA coordinator.",
    stationSetup: "Icom IC-705, Elecraft K3",
    antennaSetup: "Dipole 40m, Loop antenna",
    qslInfo: "eQSL, Bureau",
    email: "yuki@example.jp",
    phone: "",
    onAir: true,
    socialLinks: { youtube: "https://youtube.com/@ja1xyz" },
    profileViews: 2100,
    profileSearches: 420,
    cardsReceived: 45,
    cardsSent: 38,
    joinedAt: "2021-11-05",
  },
  {
    id: "4",
    callsign: "G4ABC",
    name: "James Wilson",
    avatar: "https://i.pravatar.cc/150?u=g4abc",
    location: "London, UK",
    country: "United Kingdom",
    ituZone: "ITU Zone 27",
    bio: "FT8 digital mode specialist.",
    stationSetup: "Flex 6400",
    antennaSetup: "Hexbeam, Vertical for 80m",
    qslInfo: "LoTW only",
    email: "james@example.co.uk",
    phone: "",
    onAir: false,
    socialLinks: {},
    profileViews: 756,
    profileSearches: 98,
    cardsReceived: 12,
    cardsSent: 10,
    joinedAt: "2024-01-12",
  },
];

export const qslTemplates: QSLTemplate[] = [
  {
    id: "t1",
    name: "Classic Vintage",
    backgroundColor: "#1E4D5C",
    accentColor: "#E8652A",
    borderColor: "#F5E6C8",
    isAdminCreated: true,
  },
  {
    id: "t2",
    name: "Midnight DX",
    backgroundColor: "#1A1A2E",
    accentColor: "#E94560",
    borderColor: "#F5E6C8",
    isAdminCreated: true,
  },
  {
    id: "t3",
    name: "Forest Green",
    backgroundColor: "#2D5016",
    accentColor: "#F4A020",
    borderColor: "#F5E6C8",
    isAdminCreated: true,
  },
  {
    id: "t4",
    name: "Ocean Wave",
    backgroundColor: "#0D4F6B",
    accentColor: "#FFB347",
    borderColor: "#F5E6C8",
    backgroundImage:
      "https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=600&q=80",
    isAdminCreated: true,
  },
];

export const qslCards: QSLCard[] = [
  {
    id: "q1",
    templateId: "t1",
    fromCallsign: "DL9XX",
    toCallsign: "K2ABC",
    fromName: "Max Mustermann",
    fromAddress: "Musterstr. 1, 12345 Musterstadt",
    fromCountry: "Germany",
    ituZone: "ITU Zone 28",
    date: "2024-06-15",
    utc: "14:32",
    mhz: "14.230",
    mode: "FT8",
    rst: "599",
    qslVia: "LoTW",
    status: "accepted",
    createdAt: "2024-06-15",
  },
  {
    id: "q2",
    templateId: "t1",
    fromCallsign: "K2ABC",
    toCallsign: "JA1XYZ",
    fromName: "Alex Turner",
    fromAddress: "123 Radio Lane, NY 10001",
    fromCountry: "USA",
    ituZone: "ITU Zone 8",
    date: "2024-07-02",
    utc: "08:15",
    mhz: "7.074",
    mode: "SSB",
    rst: "59",
    qslVia: "eQSL",
    status: "pending",
    createdAt: "2024-07-02",
  },
  {
    id: "q3",
    templateId: "t2",
    fromCallsign: "G4ABC",
    toCallsign: "K2ABC",
    fromName: "James Wilson",
    fromAddress: "45 Ham Street, London",
    fromCountry: "United Kingdom",
    ituZone: "ITU Zone 27",
    date: "2024-05-20",
    utc: "19:45",
    mhz: "21.074",
    mode: "FT8",
    rst: "599",
    qslVia: "LoTW",
    status: "accepted",
    createdAt: "2024-05-20",
  },
  {
    id: "q4",
    templateId: "t1",
    fromCallsign: "K2ABC",
    toCallsign: "G4ABC",
    fromName: "Alex Turner",
    fromAddress: "123 Radio Lane, NY 10001",
    fromCountry: "USA",
    ituZone: "ITU Zone 8",
    date: "2024-06-28",
    utc: "22:10",
    mhz: "14.230",
    mode: "CW",
    rst: "599",
    qslVia: "Direct",
    status: "sent",
    createdAt: "2024-06-28",
  },
];

export const networkUsers: NetworkUser[] = [
  {
    id: "2",
    callsign: "DL9XX",
    name: "Jessica Lee",
    avatar: "https://i.pravatar.cc/150?u=dl9xx",
    title: "VHF Enthusiast",
    location: "Germany",
    connectedAt: "2024-03-10",
    status: "follower",
  },
  {
    id: "3",
    callsign: "JA1XYZ",
    name: "Yuki Tanaka",
    avatar: "https://i.pravatar.cc/150?u=ja1xyz",
    title: "CW Operator",
    location: "Japan",
    connectedAt: "2024-02-15",
    status: "following",
  },
  {
    id: "4",
    callsign: "G4ABC",
    name: "James Wilson",
    avatar: "https://i.pravatar.cc/150?u=g4abc",
    title: "Digital Mode DX",
    location: "United Kingdom",
    connectedAt: "2024-04-01",
    status: "connected",
  },
  {
    id: "5",
    callsign: "VK2HAM",
    name: "Sarah Mitchell",
    avatar: "https://i.pravatar.cc/150?u=vk2ham",
    title: "Contest Operator",
    location: "Australia",
    connectedAt: "2024-05-22",
    status: "request",
  },
];

export const activities: ActivityItem[] = [
  {
    id: "a1",
    user: { callsign: "DL9XX", avatar: "https://i.pravatar.cc/150?u=dl9xx", name: "Max Mustermann" },
    content: "Just worked a new DXCC entity on 20m FT8! 73 to all.",
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?w=400&q=80",
    timestamp: "2h ago",
  },
  {
    id: "a2",
    user: { callsign: "JA1XYZ", avatar: "https://i.pravatar.cc/150?u=ja1xyz", name: "Yuki Tanaka" },
    content: "QSL card sent via LoTW. Looking forward to the confirmation!",
    timestamp: "5h ago",
  },
  {
    id: "a3",
    user: { callsign: "G4ABC", avatar: "https://i.pravatar.cc/150?u=g4abc", name: "James Wilson" },
    content: "Field day setup complete. See you on the air this weekend!",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&q=80",
    timestamp: "1d ago",
  },
];

export const analyticsData: AnalyticsData = {
  views: 1524,
  clicks: 486,
  shares: 278,
  viewsChange: 12.5,
  clicksChange: 8.3,
  sharesChange: 15.2,
  viewsOverTime: [
    { day: "Mon", views: 180 },
    { day: "Tue", views: 220 },
    { day: "Wed", views: 195 },
    { day: "Thu", views: 280 },
    { day: "Fri", views: 310 },
    { day: "Sat", views: 175 },
    { day: "Sun", views: 164 },
  ],
  trafficSources: [
    { name: "QR Code", value: 35, color: "#7C3AED" },
    { name: "WhatsApp", value: 28, color: "#25D366" },
    { name: "Social Media", value: 22, color: "#3B82F6" },
    { name: "Others", value: 15, color: "#9CA3AF" },
  ],
  recentActivity: [
    { id: "r1", message: "Your card was viewed from New York, USA", timestamp: "10 min ago" },
    { id: "r2", message: "Profile searched by DL9XX", timestamp: "1h ago" },
    { id: "r3", message: "QSL card shared via WhatsApp", timestamp: "3h ago" },
    { id: "r4", message: "Your card was viewed from Tokyo, Japan", timestamp: "5h ago" },
  ],
};

export const backgroundPresets: BackgroundPreset[] = [
  {
    id: "bg1",
    name: "Radio Waves",
    url: "https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&q=80",
    category: "radio",
  },
  {
    id: "bg2",
    name: "Antenna Tower",
    url: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80",
    category: "radio",
  },
  {
    id: "bg3",
    name: "Sunset DX",
    url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    category: "photo",
  },
  {
    id: "bg4",
    name: "Ocean",
    url: "https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=800&q=80",
    category: "photo",
  },
  {
    id: "bg5",
    name: "Purple Gradient",
    url: "linear-gradient(135deg, #2E1A47 0%, #5B3A8C 100%)",
    category: "gradient",
  },
  {
    id: "bg6",
    name: "Teal Vintage",
    url: "linear-gradient(180deg, #1E4D5C 0%, #0D3339 100%)",
    category: "gradient",
  },
];

export function getUserByCallsign(callsign: string): UserProfile | undefined {
  return users.find(
    (u) => u.callsign.toLowerCase() === callsign.toLowerCase()
  );
}

export function getTemplateById(id: string): QSLTemplate | undefined {
  return qslTemplates.find((t) => t.id === id);
}
